variables:
  Agent.Source.Git.ShallowFetchDepth: 0

steps:
- checkout: self

- powershell: .\build.ps1 publishgithubrelease --project "src\FIFOCalculator.Desktop\FIFOCalculator.Desktop.csproj"
  env:
    GitHubAuthenticationToken: $(GitHubAuthenticationToken)