variables:
  Agent.Source.Git.ShallowFetchDepth: 0

steps:
- checkout: self


- task: DotNetCoreCLI@2
  displayName: Install Android dependencies
  inputs:
    command: build
    projects: "${{ parameters.project }}"
    arguments: >
      -t:InstallAndroidDependencies
      -f:net${{ variables.DOTNET_VERSION }}-android
      -p:AcceptAndroidSDKLicenses=True
      -p:AndroidSdkPath="/usr/local/lib/android/sdk/"
      -o:$(Build.ArtifactStagingDirectory)

- powershell: .\build.ps1 publishgithubrelease
  env:
    GitHubAuthenticationToken: $(GitHubAuthenticationToken)